---
title: "RepData_PeerAssessment1"
Author: R.Shao
Time: 7/10/2017
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Mean total number of steps taken per day

```{r, echo=TRUE }
library(ggplot2)
setwd('~/Documents/coursera/repdata')
activity<-read.csv('activity.csv',header = TRUE)

total_steps<-data.frame()
for(i in unique(activity$date)){
  total_steps<-rbind(total_steps,data.frame(date=i,total_steps=sum(subset(x = activity,activity$date==i)[,1])))
}
ggplot(activity,aes(x=date,y=steps))+
  geom_bar(stat="identity")+
  xlab('')+
  theme(axis.text.x = element_text(angle = 45, hjust = 1,size = 5))


paste('The mean of total number of steps taken per day is', round(mean(x = total_steps$total_steps,na.rm=TRUE),2),', the median is',median(total_steps$total_steps,na.rm=TRUE))
```



Average daily activity pattern

```{r, echo=FALSE}
interval_steps<-data.frame()
for(i in unique(activity$interval)){
  interval_steps<-rbind(interval_steps,data.frame(interval=i,steps=mean(subset(x = activity,activity$interval==i)[,1],na.rm=TRUE)))
}
#basic plot  
plot(interval_steps,type='l')
#ggplot
ggplot(activity,aes(interval,steps))+
  stat_summary(fun.y="mean", geom="line")

paste('On average across all the days in the dataset, interval',
subset(interval_steps,steps==max(interval_steps$steps))[,1],
'contains the maximum number of steps')
```

Imputing missing values


```{r, echo=TRUE}
paste('1. The total number of missing values is', sum(is.na(activity)))

#Fill in the mean of that 5-minute interval

activity_full<-activity
activity_full$steps[is.na(activity$steps)]<-rep(interval_steps$steps,length(unique(activity$date)))[is.na(activity$steps)]

ggplot(activity_full,aes(x=date,y=steps))+
  geom_bar(stat="identity")+
  xlab('')+
  theme(axis.text.x = element_text(angle = 45, hjust = 1,size = 5))

full_total_steps<-data.frame()
for(i in unique(activity_full$date)){
  full_total_steps<-rbind(full_total_steps,data.frame(date=i,total_steps=sum(subset(x = activity_full,activity_full$date==i)[,1])))
}

paste('The mean of total number of steps taken per day is', mean(x = full_total_steps$total_steps),', the median is',median(full_total_steps$total_steps))

#After making up missing values (with the mean for that 5-minute interval), the mean of total number of steps didn't change, but the median increased up to the same value as the mean.

```

Activity patterns between weekdays and weekends

```{r, wcho=TRUE}

Week<-weekdays(as.Date(activity_full$date))%in%c( "Monday", "Tuesday", "Wednesday", "Thursday", 
    "Friday")
activity_full$day<-ifelse(Week,'Weekday','Weekend')

ggplot(activity_full,aes(x=interval,y=steps,fill=day,color=day))+
  stat_summary(fun.y="mean", geom="line")


```